name: 'Dependabot: Update pnpm lockfile'

on:
  pull_request:
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  update-pnpm-lockfile:
    name: 'Update pnpm lockfile'
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          pnpm install
          git add pnpm-lock.yaml
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git commit --amend --no-edit
          git push --force
